import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { redirect } from "next/navigation";

import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated } = getKindeServerSession();
  const isAuth = await isAuthenticated();
  if (!isAuth) {
    redirect("/onboards");
  }
  return (
    <html lang="en">
      <body className="{inter.className}">
        <nav className="h-16 m-2">
          <h1 className="text-4xl px-14">BLITZCARDS</h1>
        </nav>
        <Sidebar />
        <div className="flex">{children}</div>
      </body>
    </html>
  );
}
